### ISSUE TITLE
Not building on unix

### ISSUE THREAD

**Issue by kernelwernel** [sammwyy/NoVM#1]
![image](https://github.com/user-attachments/assets/997555e3-be0f-4995-8f41-bc879da0dc78)

**Comment by sammwyy** [comment]
Whoops, I missed that. It now compiles on Unix, however it doesn't have any defined utility for Linux/Mac or Unix-based systems.

Only the VMware implementation in Windows guest is ready. ^^ But at least it's now possible to compile NoVM from Unix. I still need to implement that part.

**Comment by kernelwernel** [comment]
> Whoops, I missed that. It now compiles on Unix, however it doesn't have any defined utility for Linux/Mac or Unix-based systems.
> 
> Only the VMware implementation in Windows guest is ready. ^^ But at least it's now possible to compile NoVM from Unix. I still need to implement that part.

Thanks! Also if it helps, I have a [VM detection project](https://github.com/kernelwernel/VMAware) which does pretty much the exact opposite of what your repository does. I figured it could be useful for you as a testing tool to see what parts you could further obfuscate to counter against VM evasion attempts.

Cool project btw, I like the idea in rust a lot :)

**Comment by sammwyy** [comment]
Woaah, that's pretty cool. I have VM(a)ware installed in my malware lab among other tools. Pretty creative name tbh :9
